'use strict';

const _ = require('lodash');
const Model = require('./video.model');

exports.get = async (req, res) => {

    try {
        const videos = await Model.find();
        res.status(200).json(videos);
    } catch (err) {
        handleError(res, err);
    }

}

exports.getVideos = async (req, res) => {

    try {
        const video = await Model.findById(req.params.id);
        // Here, you would serve the video file using the file URL stored in the database.
        // For example, using a simple file server like 'fs' module:
        const fs = require('fs');
        const fileStream = fs.createReadStream(video.fileUrl);
        fileStream.pipe(res);
    } catch (err) {
        res.status(404).send({ error: 'Video not found.' });
    }

}

exports.upload = async (req, res) => {

    // Process the uploaded file and store its metadata in MongoDB
    const model = new Model({
        title: req.body.title,
        description: req.body.description,
        fileUrl: req.file.path, // Store the temporary file path generated by multer
        fileSize: req.file.size,
        created_by: req.user._id
    });
    // console.info(model)
    try {
        await model.save();
        res.status(200).json({ data: 'Video uploaded successfully!' });
    } catch (err) {
        res.status(500).send({ error: 'Error uploading video.' });
    }

}